### ISSUE TITLE
More thoughtful checking of arguments

### ISSUE THREAD

**Issue by mohawkjohn** [Arafatk/magick-rubyplot#2]
https://github.com/Arafatk/magick-rubyplot/blob/4969fd3e34c14652de452e7d1d33268581667593/lib/rubyplot/artist/scatter/data.rb#L37

Some of this is a bit subjective, but I think it's important to discuss.

You can't check every single argument's validity. There are too many wrong values people can plug in.

Ask yourself the following questions:
* Does my error check add an error message where there would otherwise be a totally unhandled error? (If a later call would produce an error message for this invalid argument, you probably don't need it unless it's an exceedingly common mistake.)
* How long will this error check take? (Checking each data array for nil is going to be time-consuming. Are you sure you can't find a more clever way to accomplish this check?)
* Am I raising the right kind of exception here? (Some of these should almost certainly be ValueErrors, I think.)

There are probably others, too. @v0dro, care to weigh in?

I'm also concerned about some of your argument names here.

Why do you have an underscore on `_color`? Is `x_data_points` needed in lieu of just `x` for some reason? These seem like odd decisions, and I'd like you to explain your rationale for them when you have a moment.

**Comment by v0dro** [comment]
So I think the problem is that you need to learn to write more idiomatic Ruby code than what you are writing now. There is almost never a case where people check the internals of a Ruby array. If the user has supplied a wrong value it will be detected by image-magick, and your Ruby layer can catch and throw that error instead.

In the usual case you will ideally be using a numerical container library like nmatrix or narray for supplying data. Once you shift to those, these checks will no longer be necessary.

Scroll page 15 of the confident ruby [book](https://www.scribd.com/document/266755485/Avdi-Grimm-Confident-Ruby-pdf). Read the section titled 'four parts of a method'.

In it, the author is expressing that a Ruby method should as terse and 'confident' as possible. Argument checking code is generally looked down upon in Ruby.

**Comment by Arafatk** [comment]
Hi John,    
That's a very valid concern so thanks a lot for raising it sooner rather than later.    
I personally thought of similar questions about the error handling when I was thinking of doing error handling and to be fair, I have left a bit of it because I was ambivalent of how far I should take my error handling code. Also, it does tend to make it difficult to make changes to the code fast.          

It's uncanny how Avdi's book highlights what I thought a bit myself and also given that I will eventually move on to numerical container libraries a lot of these checks might be redundant(I will remove them soon).      
Let's keep the issue on just in case I have questions about this.

**Comment by mohawkjohn** [comment]
Several thumbs up to what @v0dro is saying.

**Comment by Arafatk** [comment]
@pgtgrly  This is my stance on Error checking too.      
It's very hard to do this the right way so I am removing argument error checks from projects completely for now and when we move to NMatrix in the future things will take care of themselves.
